version: '3'

networks:
  appnet:
    driver: "bridge"

volumes:
  data:
    driver: "local"

services:
  db:
    image: mysql:latest
    container_name: tweet-scheduler-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - appnet

  mail:
    image: mailhog/mailhog:latest
    container_name: tweet-scheduler-mail
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - appnet

  redis:
    image: redis:alpine
    container_name: tweet-scheduler-redis
    ports:
      - "6379:6379"
    networks:
      - appnet
